# Pre-commit example taken from https://github.com/pocc/pre-commit-hooks/blob/master/README.md
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [-i,--style=Google]